Created starting delivery and plugin system
pgayee694/PKIIPS pull request #16
Opened 2020-02-27 22:04 UTC by mooncollin

Created primitive plugin system for the seer platform. Plugins are created by putting python files in the plugins folder and it will automatically pick up any classes that inherit from the data_collector_plugin class.

Examples are in the test.py plugin. Currently, the delivery system is just printing out to the console. It will eventually be communicating JSON to a server.

2020-02-28 03:07 UTC, pgayee694 requested changes

2020-02-28 03:07 UTC, pgayee694 commented on seers/plugins/test.py
> +from seer import data_collector_plugin
this should be moved into it's own directory like `tests/`

2020-02-28 03:07 UTC, pgayee694 commented on seers/plugins/__init__.py
> +	plugins = []
documentation

2020-02-28 03:07 UTC, pgayee694 commented on seers/seer.py
> +	def __init__(self):
documentation on the object and the rest of the functions/object declarations in this file

2020-02-28 03:07 UTC, pgayee694 commented on seers/seer.py
> +import plugins
imports should be at the top of the file

2020-02-28 03:07 UTC, pgayee694 commented on seers/seer.py
> +if __name__ == '__main__':
move this to it's own file

2020-02-28 03:07 UTC, pgayee694 commented on seers/plugins/test.py
> +# class camera_collector2(data_collector_plugin):
why is this commented out?

2020-02-29 22:02 UTC, pgayee694 requested changes

2020-02-29 22:02 UTC, pgayee694 commented on seers/plugins/__init__.py
> +__all__ = [os.path.basename(f)[:-len(PYTHON_EXTENSION)] for f in modules if os.path.isfile(f) and os.path.basename(f) not in IGNORED_FILES]
don't search for files, have the entry point instantiate all the seers you want to collect and reference/manipulate them that way; then we can just maintain that along with enums

2020-02-29 22:02 UTC, pgayee694 commented on seers/plugins/tests/test.py
> +import seer_plugin
might want to reconsider naming this file to something like "test_plugin" or something to differentiate it from unit tests and then have unit tests that use it to test the functionality

2020-02-29 22:02 UTC, pgayee694 commented on seers/seer.py
> +timeout			= None if seer_config.data_collection_timeout is None else seer_config.data_collection_timeout / 1000
/nit wierd spacing?

2020-02-29 22:02 UTC, pgayee694 commented on seers/seer_config.py
> +general_ini					= 'general'
/nit wierd spacing again?

2020-02-29 22:02 UTC, pgayee694 commented on seers/plugins/tests/test.py
> +class test_collector(object):
classes should be renamed in pep8 convention, i.e. TestCollector

2020-02-29 22:02 UTC, pgayee694 commented on seers/seer_config.py
> +import configparser
Should this be a class?

2020-02-29 22:02 UTC, pgayee694 commented on seers/seer_plugin.py
> +class data_collector_plugin(object):
/nit Consider naming this something like "AbstractDataCollectorPlugin" or "DataCollectorPluginBase" to make sure it's easily recognizable as the base class

2020-02-29 22:28 UTC, svnphlps commented on seers/seer_plugin.py
> +def plugin_collection(plug_class, message_queue, stop_token):
Maybe rename this function to 'collect_data'.

2020-03-01 02:26 UTC, mooncollin commented on seers/seer_config.py
> +general_ini					= 'general'
Git does that. It's not the source

2020-03-01 18:39 UTC, pgayee694 approved these changes

2020-03-02 00:11 UTC, svnphlps approved these changes

2020-03-02 00:13 UTC, merged