delphi client template
pgayee694/PKIIPS pull request #43
Opened 2020-04-09 00:26 UTC by svnphlps

close #35

2020-04-10 19:17 UTC, pgayee694 commented on oracle/Assets/Scripts/DelphiClient.cs
> +  private readonly string GET_NODES_URL = "";
Is there a way we can pass command line arguments to the Unity app to give it the url of delphi? @mooncollin

2020-04-11 20:12 UTC, pgayee694 commented on oracle/Assets/Scripts/DelphiClient.cs
> +  private readonly string GET_NODES_URL = "";
using a config file

2020-04-18 20:31 UTC, pgayee694 requested changes

2020-04-18 20:31 UTC, pgayee694 commented on oracle/Assets/Scripts/DelphiClient.cs
> +    UnityWebRequest www = UnityWebRequest.Get(BASE_URL + "/get-statuses?room_ids=" + string.Join(",", roomIds));
the url needs '&' between each room id
i.e.  "/get-statuses?room_id=260&room_id=261"

2020-04-18 20:31 UTC, pgayee694 commented on oracle/Assets/Scripts/DelphiClient.cs
> +    UnityWebRequest www = UnityWebRequest.Get(BASE_URL + "/get-counts?room_ids=" + string.Join(",", roomIds));
same as above

2020-04-23 19:52 UTC, mooncollin approved these changes

2020-04-24 17:32 UTC, pgayee694 commented
looks good, just fix your rebase or merge master into your branch

2020-04-24 19:44 UTC, pgayee694 commented
provide a default config.ini

2020-04-24 19:55 UTC, pgayee694 approved these changes

2020-04-24 19:56 UTC, merged