Node endpoints
pgayee694/PKIIPS pull request #45
Opened 2020-04-13 02:52 UTC by pgayee694

2020-04-13 20:38 UTC, mooncollin requested changes

2020-04-13 20:38 UTC, mooncollin commented on delphi/app/routes.py
> +@app.route('/enable/<room_id>', methods=['PUT'])
It looks like room id is expected to be an integer. To force it, you can use: /enable/<int:room_id>, so you don't need to cast to int later on and I believe flask won't allow that route to go through if it isn't an int.

2020-04-13 20:38 UTC, mooncollin commented on delphi/app/routes.py
> +    rooms = [int(r) for r in request.args.getlist('room_id')]
If these room ids are expected to be unique, I'd suggest using a set here.

2020-04-16 00:20 UTC, mooncollin approved these changes
Looks good!

2020-04-16 00:25 UTC, svnphlps approved these changes

2020-04-16 01:03 UTC, merged